# Site settings
title: Stats Beerz Archive
description: > # this means to ignore newlines until "baseurl:"
  An archive of useful Stats Beerz emails and links
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sfu-stats-beerz.github.io" # the base hostname & protocol for your site
twitter_username: statsbeerz
github_username:  sfu-stats-beerz

# Build settings
markdown: kramdown
